USE master;
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'Product')
BEGIN
    CREATE DATABASE Product;
END
GO

USE Product;
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PRODUCTTYPE]') AND type in (N'U'))
BEGIN
    CREATE TABLE PRODUCTTYPE (
        PRODUCTTYPEID VARCHAR(5) NOT NULL PRIMARY KEY,
        PRODUCTTYPENAME NVARCHAR(50) NOT NULL
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PRODUCTMASTER]') AND type in (N'U'))
BEGIN
    CREATE TABLE PRODUCTMASTER (
        PRODUCTID VARCHAR(20) NOT NULL PRIMARY KEY,
        PRODUCTNAME NVARCHAR(50) NOT NULL,
        PRODUCTTYPEID VARCHAR(5) NOT NULL,
        PRODUCTSTATUS INT NOT NULL DEFAULT 0, -- 0 ใช้งาน, 9 ยกเลิก
        CREATEUSER VARCHAR(20) NOT NULL,
        CREATEDATE DATETIME NOT NULL DEFAULT GETDATE(),
        UPDATEUSER VARCHAR(20) NULL,
        UPDATEDATE DATETIME NULL,
        CONSTRAINT FK_PRODUCTMASTER_PRODUCTTYPE
            FOREIGN KEY (PRODUCTTYPEID)
            REFERENCES PRODUCTTYPE(PRODUCTTYPEID)
    );
END
GO

ALTER TABLE PRODUCTTYPE ALTER COLUMN PRODUCTTYPENAME NVARCHAR(50) NOT NULL;
ALTER TABLE PRODUCTMASTER ALTER COLUMN PRODUCTNAME NVARCHAR(50) NOT NULL;
GO

IF NOT EXISTS (SELECT 1 FROM PRODUCTTYPE WHERE PRODUCTTYPEID = 'B')
    INSERT INTO PRODUCTTYPE (PRODUCTTYPEID, PRODUCTTYPENAME) VALUES ('B', N'เสื้อชั้นใน');
ELSE
    UPDATE PRODUCTTYPE SET PRODUCTTYPENAME = N'เสื้อชั้นใน' WHERE PRODUCTTYPEID = 'B';

IF NOT EXISTS (SELECT 1 FROM PRODUCTTYPE WHERE PRODUCTTYPEID = 'U')
    INSERT INTO PRODUCTTYPE (PRODUCTTYPEID, PRODUCTTYPENAME) VALUES ('U', N'กางเกงใน');
ELSE
    UPDATE PRODUCTTYPE SET PRODUCTTYPENAME = N'กางเกงใน' WHERE PRODUCTTYPEID = 'U';
GO

SELECT * FROM PRODUCTTYPE;